Config updates, pages Updates
Ragimzade/QulixTeachingSite pull request #1
Opened 2019-08-29 09:45 UTC by Ragimzade

2019-08-29 12:03 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/model/ConfigFileReader.java
x

2019-08-29 12:14 UTC, alexeyrakitsky requested changes

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/model/ConfigFileReader.java
> +    protected InputStream input = ConfigFileReader.class.getClassLoader().getResourceAsStream("config.properties"); //todo я говорил, использовать class.getResourceAsStream
Нет. Стримы не надо хранить как поля

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/model/ConfigFileReader.java
> +        return prop.getProperty("explicitWaits");
А почему это возвращает стринг?

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/LoginPage.java
> +        return new WebDriverWait(driver, Long.parseLong(config.getExplicitWait()))
вот самый первый комент здесь был по-моему об этом. Твой метод в таком исполнении может вернуть true либо выкинуть Exception. Он никогда не вернет false.

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/model/ConfigFileReader.java
>  package model;
Почему конфиг в model?

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    ConfigFileReader config;
1. Это в принципе не стоит хранить как поле
2. В этом классе поле с уровнем доступа package не логично. Это базовый класс страниц. В твоем случае всего 5 страниц, но в целом то приложения имеют десятки/сотни страниц и там по-любому будет структурирование по подпакетам

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
>      public void enterValue(WebElement field, String value) {
А мне откуда знать, что сюда я должен передавать WrappedElement?

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +        //В принципе можно определить проверкой чек-бокса "Show messages of all users", но ладно не буду
Я тебе выше написал, а если чекбокс не работает (дефект)? Если чекбок выбран как раз "Все пользователи"?

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
какая-то неочевидная логика работы. Параметр isAuthorRequired по имени не соответствует тому, как он используется

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/resources/config.properties
> +explicitWaits = 1
это называется timeout

2019-08-29 12:14 UTC, alexeyrakitsky commented on QulixTeachingSite/target/classes/config.properties
>  baseUrl = http://localhost:8080/QulixTeachingSite/
target папки в git быть не должно

2019-08-29 13:02 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
ну типа "Нужен ли автор для теста", "isAuthorVerifyRequired" - так лучше?

2019-08-29 13:02 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +        //В принципе можно определить проверкой чек-бокса "Show messages of all users", но ладно не буду
"Если чекбок выбран как раз "Все пользователи"?" -  что мешает отжать?)
Ну да, если только сломан чекбокс

2019-08-29 13:03 UTC, Ragimzade commented on QulixTeachingSite/target/classes/config.properties
>  baseUrl = http://localhost:8080/QulixTeachingSite/
ок, добавлю в игнор

2019-08-29 13:03 UTC, Ragimzade commented on QulixTeachingSite/src/main/resources/config.properties
> +explicitWaits = 1
timeout общее название, explicitWait - конкретный тип ожиданий

2019-08-29 13:07 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    ConfigFileReader config;
а когда тогда, создавать сразу объект класса
 "ConfigFileReader config = new ConfigFileReader();" ?

2019-08-29 13:16 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    ConfigFileReader config;
Singleton

2019-08-29 13:18 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +        //В принципе можно определить проверкой чек-бокса "Show messages of all users", но ладно не буду
Кто его должен отжать

2019-08-29 13:19 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
Нет. Я не понимаю все равно за что этот флаг отвечает. В чем разница true он или false?

2019-08-29 13:21 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/resources/config.properties
> +explicitWaits = 1
explicitWait - это тип ожиданий Selenium и что в таком случае значит 1? Если очень хочется, то explcitWaitTimeout. И вот ты отдаешь на сторону свой проект и как я должен догадаться за какие ожидания этот таймаут отвечает? Почем мне знать где и как ты используешь Explicit Wait. Параметры должны отвечать за бизнес, а не технику

2019-08-29 13:26 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
если true - вытягивает из формы  headline, text и author
если false - только headline и text

2019-08-29 13:30 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
а почему нельзя все время брать все данные?

2019-08-29 13:31 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +        //В принципе можно определить проверкой чек-бокса "Show messages of all users", но ладно не буду
тесты

2019-08-29 13:35 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/PageBase.java
>      public void enterValue(WebElement field, String value) {
ты наверно тут имел ввиду метод "isElementPresent"?

2019-08-29 13:48 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +        //В принципе можно определить проверкой чек-бокса "Show messages of all users", но ладно не буду
ну вот как ты себе это видишь? Я, создавая тест, должен еще думать и помнить... Ааа, вот тут для корректной работы мне надо выбрать только свои сообщения.  А если по тесту мне надо открыть именно другого пользователя, то все, гамон. Тест не автоматизируемым становится?

2019-08-29 13:48 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
>      public void enterValue(WebElement field, String value) {
наверное

2019-08-29 13:49 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
потому что есть метод "getEditFormData()", где я не могу определить автора, и если в тестах сравниваю эти две формы, а в одном из них автор = null, тесты падают

2019-08-29 13:49 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
ну так исправляй методы сравнения, а не ты плодишь какие-то непонятные флаги

2019-08-29 14:45 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
вполне нормальный флаг и всего один. Ок, сделаю метод сравнения этих двух форм

2019-08-29 15:08 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
В каком месте он нормальный? У тебя метод называет getMessageData - получить данные сообщения. И он внезапно просит какой-то булевый параметр. Первая мысль - что за пи..ц там происходит. Первое, о чем нужно думать, создавая публичные методы (имена, параметры) - то насколько очевидно название метода и запрашиваемые им параметры (по типу, а не по названию) для стороннего человека. Флаги имеют право на жизнь, но только там, где они реально полезны.
Почитай https://oz.by/books/more10109592.html
+ в комментариях там еще хвалят книгу "Code complete", как вариант и ее почитать.

2019-08-29 15:16 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
почитаю, спасибо

2019-08-30 15:41 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/ShowMessage.java
> +    public MessageData getMessageData(boolean isAuthorRequired) {
![QulixTeachingSite](https://user-images.githubusercontent.com/49450464/64033522-5037be80-cb55-11e9-9e25-da4631c8e20c.png)
Сделал такие ассерты в тестовом классе. Или лучше вынести эти два ассерта в 1 метод?

2019-09-03 17:08 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/CreateMessage.java
123

2019-09-04 08:12 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
>      ConfigFileReader instance = ConfigFileReader.getInstance();
Почему именно package level?

2019-09-04 08:12 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/MessageList.java
> +        try {
почему не isElementPresent?

2019-09-04 08:12 UTC, alexeyrakitsky commented on QulixTeachingSite/.gitignore
> +target/
помимо простого добавления в gitignore файлы надо еще удалить из ветки физически.
target можно просто удалить в впушить
.idea  - перемести в другое место. Впуш, будто папка удалена из гита и потом верни папку обратно

2019-09-04 08:12 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    ConfigFileReader instance = ConfigFileReader.getInstance();
что за название instance?

2019-09-04 08:12 UTC, alexeyrakitsky commented on QulixTeachingSite/src/test/java/ft/TestBase.java
> +        ConfigFileReader instance = ConfigFileReader.getInstance();
опять какой-то instance

2019-09-04 08:19 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/MessageList.java
> +        try {
да надо тут isElementPresent, забыл

2019-09-04 08:21 UTC, Ragimzade commented on QulixTeachingSite/.gitignore
> +target/
а вон оно че, а я не мог понять, почему не работает

2019-09-06 08:19 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
>      ConfigFileReader config = configFileReader.getInstance();
не пойму, что за configFileReader и config?

2019-09-06 08:19 UTC, alexeyrakitsky commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    protected ConfigFileReader config = configFileReader.getInstance();
а зачем ты создаешь configFileReader для получения instance?

2019-09-06 10:23 UTC, Ragimzade commented on QulixTeachingSite/src/main/java/pages/PageBase.java
> +    protected ConfigFileReader config = configFileReader.getInstance();
Поправил вроде. Что-то не до конца разобрался с синглтонами, почитаю еще.

2019-09-06 12:14 UTC, alexeyrakitsky approved these changes

2019-09-06 12:15 UTC, merged